### ISSUE TITLE
RuntimeException: Can't find requested test UnsafeArrayList EightLongs

### ISSUE THREAD

**Issue by aewhite** [bramp/unsafe#1]
I was trying to run the benchmarks when the following error appeared in several runs.

```
# JMH 1.10.4 (released 17 days ago)
# VM version: JDK 1.8.0_05, VM 25.5-b02
# VM invoker: /Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/bin/java
# VM options: -Xmx16g
# Warmup: 2 iterations, 10 s each
# Measurement: 5 iterations, 60 s each
# Timeout: 10 min per iteration
# Threads: 1 thread, will synchronize iterations
# Benchmark mode: Average time, time/op
# Benchmark: net.bramp.unsafe.collection.ArrayListBenchmark.testSort
# Parameters: (list = UnsafeArrayList, size = 20000000, type = FourLongs)

# Run progress: 77.78% complete, ETA 00:00:20
# Fork: 1 of 1
# Warmup Iteration   1: <failure>

java.lang.RuntimeException: Can't find requested test UnsafeArrayList FourLongs
	at net.bramp.unsafe.collection.ArrayListBenchmark.setup(ArrayListBenchmark.java:55)
	at net.bramp.unsafe.collection.generated.ArrayListBenchmark_testSort._jmh_tryInit_f_arraylistbenchmark0_0(ArrayListBenchmark_testSort.java:309)
	at net.bramp.unsafe.collection.generated.ArrayListBenchmark_testSort.testSort_AverageTime(ArrayListBenchmark_testSort.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:430)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:412)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bramp** [comment]
Sorry about this, I broke this by mistake while cleaning up some code.
